- thing: MFPS 2022
  role: Program Committee
  links:
	site: ??
- thing: ECOOP Doctoral Symposium
  role: Program Committee

- thing: MSFP 2022
  role: Co-chair
  links:
	site: https://msfp-workshop.github.io/msfp2022/

- thing: HATRA 2021
  role: Program Committee
  links:
	??

- thing: ICFP 2021
  role: Program Committee Member

- thing: MSFP 2020
  role: Co-chair
  links:
	site: https://msfp-workshop.github.io/msfp2020/

- thing: HATRA 2020
  role: Program Committee
  links:
	??

- thing: New England Programming Languages Seminar (NEPLS), August 2018
  role: Speaker Selection Committee

- thing: New England Programming Languages Seminar (NEPLS), June 2017
  role: Speaker Selection Committee

- thing: New England Programming Languages Seminar (NEPLS), October 2016
  role: Co-chair
